// <auto-generated />
using System;
using KozossegAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KozossegAPI.Migrations
{
    [DbContext(typeof(KozossegDbContext))]
    [Migration("20260622012807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KozossegAPI.Model.Ceg", b =>
                {
                    b.Property<int>("ceg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ceg_id");

                    b.Property<string>("adoszam")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("adoszam");

                    b.Property<string>("ceg_email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ceg_email");

                    b.Property<string>("cegnev")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cegnev");

                    b.Property<string>("cim")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cim");

                    b.Property<int>("is_active")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<string>("jelszo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("jelszo");

                    b.Property<string>("telefonszam")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefonszam");

                    b.Property<string>("verification_token")
                        .HasColumnType("longtext")
                        .HasColumnName("verification_token");

                    b.HasKey("ceg_id");

                    b.ToTable("Ceg");
                });

            modelBuilder.Entity("KozossegAPI.Model.Diak", b =>
                {
                    b.Property<int>("diak_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("diak_id");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("igazolas_pdf")
                        .HasColumnType("longtext")
                        .HasColumnName("igazolas_pdf");

                    b.Property<int>("is_active")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<string>("iskola")
                        .HasColumnType("longtext")
                        .HasColumnName("iskola");

                    b.Property<string>("iskola_om_kod")
                        .HasColumnType("longtext")
                        .HasColumnName("iskola_om_kod");

                    b.Property<string>("jelszo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("jelszo");

                    b.Property<int>("ledolgozott_ora")
                        .HasColumnType("int")
                        .HasColumnName("ledolgozott_ora");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nev");

                    b.Property<string>("om_azonosito")
                        .HasColumnType("longtext")
                        .HasColumnName("om_azonosito");

                    b.Property<string>("osztaly")
                        .HasColumnType("longtext")
                        .HasColumnName("osztaly");

                    b.Property<string>("telefonszam")
                        .HasColumnType("longtext")
                        .HasColumnName("telefonszam");

                    b.Property<string>("verification_token")
                        .HasColumnType("longtext")
                        .HasColumnName("verification_token");

                    b.HasKey("diak_id");

                    b.ToTable("Diak");
                });

            modelBuilder.Entity("KozossegAPI.Model.Dokumentum", b =>
                {
                    b.Property<int>("doku_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("doku_id");

                    b.Property<DateTime>("alairas_datuma")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("alairas_datuma");

                    b.Property<int>("ceg_id")
                        .HasColumnType("int")
                        .HasColumnName("ceg_id");

                    b.Property<string>("pdf_link")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pdf_link");

                    b.HasKey("doku_id");

                    b.HasIndex("ceg_id");

                    b.ToTable("Dokumentum");
                });

            modelBuilder.Entity("KozossegAPI.Model.Jelentkezes", b =>
                {
                    b.Property<int>("munka_id")
                        .HasColumnType("int")
                        .HasColumnName("munka_id");

                    b.Property<int>("diak_id")
                        .HasColumnType("int")
                        .HasColumnName("diak_id");

                    b.Property<string>("igazolas_adatok")
                        .HasColumnType("longtext")
                        .HasColumnName("igazolas_adatok");

                    b.Property<DateTime>("jelentkezes_ideje")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("jelentkezes_ideje");

                    b.Property<int>("jovahagyott_ora")
                        .HasColumnType("int")
                        .HasColumnName("jovahagyott_ora");

                    b.Property<string>("munka_statusz")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("munka_statusz");

                    b.HasKey("munka_id", "diak_id");

                    b.HasIndex("diak_id");

                    b.ToTable("Jelentkezes");
                });

            modelBuilder.Entity("KozossegAPI.Model.Munka", b =>
                {
                    b.Property<int>("munka_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("munka_id");

                    b.Property<int>("ceg_id")
                        .HasColumnType("int")
                        .HasColumnName("ceg_id");

                    b.Property<string>("cim")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cim");

                    b.Property<DateTime>("idopont")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("idopont");

                    b.Property<string>("kategoria")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("kategoria");

                    b.Property<string>("leiras")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("leiras");

                    b.Property<int>("letszam")
                        .HasColumnType("int")
                        .HasColumnName("letszam");

                    b.Property<string>("munka_nev")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("munka_nev");

                    b.Property<int>("oraszam")
                        .HasColumnType("int")
                        .HasColumnName("oraszam");

                    b.Property<string>("statusz")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("statusz");

                    b.HasKey("munka_id");

                    b.HasIndex("ceg_id");

                    b.ToTable("Munka");
                });

            modelBuilder.Entity("KozossegAPI.Model.Dokumentum", b =>
                {
                    b.HasOne("KozossegAPI.Model.Ceg", "Ceg")
                        .WithMany("Dokumentumok")
                        .HasForeignKey("ceg_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("KozossegAPI.Model.Jelentkezes", b =>
                {
                    b.HasOne("KozossegAPI.Model.Diak", "Diak")
                        .WithMany()
                        .HasForeignKey("diak_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KozossegAPI.Model.Munka", "Munka")
                        .WithMany()
                        .HasForeignKey("munka_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diak");

                    b.Navigation("Munka");
                });

            modelBuilder.Entity("KozossegAPI.Model.Munka", b =>
                {
                    b.HasOne("KozossegAPI.Model.Ceg", "Ceg")
                        .WithMany()
                        .HasForeignKey("ceg_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("KozossegAPI.Model.Ceg", b =>
                {
                    b.Navigation("Dokumentumok");
                });
#pragma warning restore 612, 618
        }
    }
}
